# Generated by Django 5.0.4 on 2024-05-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_computers_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
